Search.appendIndex(
    [
                {
            "fqsen": "\\autoLoadPHPClasses\u0028\u0029",
            "name": "autoLoadPHPClasses",
            "summary": "Autoload\u0020PHP\u0020Classes",
            "url": "namespaces/default.html#function_autoLoadPHPClasses"
        },                {
            "fqsen": "\\Controllers\\AdminController",
            "name": "AdminController",
            "summary": "AdminController",
            "url": "classes/Controllers-AdminController.html"
        },                {
            "fqsen": "\\Controllers\\AdminController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Controllers-AdminController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\AdminController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020admin\u0020dashboard\u0020page.",
            "url": "classes/Controllers-AdminController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\AdminController\u003A\u003AloadUsers\u0028\u0029",
            "name": "loadUsers",
            "summary": "Load\u0020users\u0020from\u0020the\u0020database.",
            "url": "classes/Controllers-AdminController.html#method_loadUsers"
        },                {
            "fqsen": "\\Controllers\\AdminController\u003A\u003AloadArticles\u0028\u0029",
            "name": "loadArticles",
            "summary": "Load\u0020articles\u0020from\u0020the\u0020database.",
            "url": "classes/Controllers-AdminController.html#method_loadArticles"
        },                {
            "fqsen": "\\Controllers\\AdminController\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/Controllers-AdminController.html#property_page"
        },                {
            "fqsen": "\\Controllers\\ArticleController",
            "name": "ArticleController",
            "summary": "ArticleController",
            "url": "classes/Controllers-ArticleController.html"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Controllers-ArticleController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020appropriate\u0020webpage\u0020based\u0020on\u0020the\u0020action.",
            "url": "classes/Controllers-ArticleController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003AgetArticles\u0028\u0029",
            "name": "getArticles",
            "summary": "Retrieve\u0020articles\u0020from\u0020the\u0020database.",
            "url": "classes/Controllers-ArticleController.html#method_getArticles"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003AaddArticle\u0028\u0029",
            "name": "addArticle",
            "summary": "Add\u0020a\u0020new\u0020article\u0020to\u0020the\u0020database.",
            "url": "classes/Controllers-ArticleController.html#method_addArticle"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003AeditArticle\u0028\u0029",
            "name": "editArticle",
            "summary": "Edit\u0020an\u0020existing\u0020article\u0020in\u0020the\u0020database.",
            "url": "classes/Controllers-ArticleController.html#method_editArticle"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003AdeleteArticle\u0028\u0029",
            "name": "deleteArticle",
            "summary": "Delete\u0020an\u0020article\u0020and\u0020all\u0020its\u0020associated\u0020images.",
            "url": "classes/Controllers-ArticleController.html#method_deleteArticle"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003AdeleteArticleImage\u0028\u0029",
            "name": "deleteArticleImage",
            "summary": "Delete\u0020a\u0020single\u0020image\u0020from\u0020an\u0020article.",
            "url": "classes/Controllers-ArticleController.html#method_deleteArticleImage"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/Controllers-ArticleController.html#property_page"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003A\u0024editorPage",
            "name": "editorPage",
            "summary": "",
            "url": "classes/Controllers-ArticleController.html#property_editorPage"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003A\u0024action",
            "name": "action",
            "summary": "",
            "url": "classes/Controllers-ArticleController.html#property_action"
        },                {
            "fqsen": "\\Controllers\\ArticleController\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/Controllers-ArticleController.html#property_validator"
        },                {
            "fqsen": "\\Controllers\\Controller",
            "name": "Controller",
            "summary": "Controller",
            "url": "classes/Controllers-Controller.html"
        },                {
            "fqsen": "\\Controllers\\Controller\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020specified\u0020webpage.",
            "url": "classes/Controllers-Controller.html#method_render"
        },                {
            "fqsen": "\\Controllers\\Controller\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/Controllers-Controller.html#property_page"
        },                {
            "fqsen": "\\Controllers\\ErrorController",
            "name": "ErrorController",
            "summary": "ErrorController",
            "url": "classes/Controllers-ErrorController.html"
        },                {
            "fqsen": "\\Controllers\\ErrorController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ErrorController\u0020constructor.",
            "url": "classes/Controllers-ErrorController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\ErrorController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020error\u0020page.",
            "url": "classes/Controllers-ErrorController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\ErrorController\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Controllers-ErrorController.html#property_path"
        },                {
            "fqsen": "\\Controllers\\ErrorController\u003A\u003A\u0024errorCode",
            "name": "errorCode",
            "summary": "",
            "url": "classes/Controllers-ErrorController.html#property_errorCode"
        },                {
            "fqsen": "\\Controllers\\HomepageController",
            "name": "HomepageController",
            "summary": "HomepageController",
            "url": "classes/Controllers-HomepageController.html"
        },                {
            "fqsen": "\\Controllers\\HomepageController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Renders\u0020the\u0020homepage\u0020view.",
            "url": "classes/Controllers-HomepageController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\HomepageController\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Controllers-HomepageController.html#property_path"
        },                {
            "fqsen": "\\Controllers\\LoginController",
            "name": "LoginController",
            "summary": "Login\u0020page\u0020controller",
            "url": "classes/Controllers-LoginController.html"
        },                {
            "fqsen": "\\Controllers\\LoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Controllers-LoginController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\LoginController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020login\u0020page\u0020view.",
            "url": "classes/Controllers-LoginController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\LoginController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Process\u0020the\u0020user\u0020login\u0020request.",
            "url": "classes/Controllers-LoginController.html#method_login"
        },                {
            "fqsen": "\\Controllers\\LoginController\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Controllers-LoginController.html#property_path"
        },                {
            "fqsen": "\\Controllers\\LoginController\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/Controllers-LoginController.html#property_validator"
        },                {
            "fqsen": "\\Controllers\\NewsController",
            "name": "NewsController",
            "summary": "NewsController",
            "url": "classes/Controllers-NewsController.html"
        },                {
            "fqsen": "\\Controllers\\NewsController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020News\u0020webpage\u0020view.",
            "url": "classes/Controllers-NewsController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\NewsController\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/Controllers-NewsController.html#property_page"
        },                {
            "fqsen": "\\Controllers\\RegisterController",
            "name": "RegisterController",
            "summary": "RegisterController",
            "url": "classes/Controllers-RegisterController.html"
        },                {
            "fqsen": "\\Controllers\\RegisterController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "RegisterController\u0020constructor.",
            "url": "classes/Controllers-RegisterController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\RegisterController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020registration\u0020webpage.",
            "url": "classes/Controllers-RegisterController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\RegisterController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Process\u0020the\u0020user\u0020registration\u0020workflow.",
            "url": "classes/Controllers-RegisterController.html#method_register"
        },                {
            "fqsen": "\\Controllers\\RegisterController\u003A\u003A\u0024page",
            "name": "page",
            "summary": "The\u0020absolute\u0020path\u0020to\u0020the\u0020\u0060register.php\u0060\u0020view\u0020file.",
            "url": "classes/Controllers-RegisterController.html#property_page"
        },                {
            "fqsen": "\\Controllers\\RegisterController\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "Validator\u0020instance\u0020for\u0020validating\u0020user\u0020input\u0020fields.",
            "url": "classes/Controllers-RegisterController.html#property_validator"
        },                {
            "fqsen": "\\Controllers\\TestingController",
            "name": "TestingController",
            "summary": "Controller",
            "url": "classes/Controllers-TestingController.html"
        },                {
            "fqsen": "\\Controllers\\TestingController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "TestingController\u0020constructor",
            "url": "classes/Controllers-TestingController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\TestingController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020testing\u0020page\u0020view",
            "url": "classes/Controllers-TestingController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\TestingController\u003A\u003AtestImageUpload\u0028\u0029",
            "name": "testImageUpload",
            "summary": "Test\u0020image\u0020uploading\u0020functionality",
            "url": "classes/Controllers-TestingController.html#method_testImageUpload"
        },                {
            "fqsen": "\\Controllers\\TestingController\u003A\u003AtestXhr\u0028\u0029",
            "name": "testXhr",
            "summary": "Test\u0020XHR\u0020response\u0020for\u0020AJAX\u0020requests",
            "url": "classes/Controllers-TestingController.html#method_testXhr"
        },                {
            "fqsen": "\\Controllers\\TestingController\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/Controllers-TestingController.html#property_page"
        },                {
            "fqsen": "\\Controllers\\TestingController\u003A\u003A\u0024subPage",
            "name": "subPage",
            "summary": "",
            "url": "classes/Controllers-TestingController.html#property_subPage"
        },                {
            "fqsen": "\\Controllers\\UserController",
            "name": "UserController",
            "summary": "Controller",
            "url": "classes/Controllers-UserController.html"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Controllers-UserController.html#method___construct"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020appropriate\u0020webpage\u0020based\u0020on\u0020the\u0020action.",
            "url": "classes/Controllers-UserController.html#method_render"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003AgetUsers\u0028\u0029",
            "name": "getUsers",
            "summary": "Retrieve\u0020users\u0020from\u0020the\u0020database.",
            "url": "classes/Controllers-UserController.html#method_getUsers"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003AloadUserData\u0028\u0029",
            "name": "loadUserData",
            "summary": "Load\u0020the\u0020currently\u0020authenticated\u0020user\u0027s\u0020data.",
            "url": "classes/Controllers-UserController.html#method_loadUserData"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003AupdateFullname\u0028\u0029",
            "name": "updateFullname",
            "summary": "Update\u0020the\u0020full\u0020name\u0020of\u0020the\u0020logged\u002Din\u0020user.",
            "url": "classes/Controllers-UserController.html#method_updateFullname"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003AupdateProfileImage\u0028\u0029",
            "name": "updateProfileImage",
            "summary": "Update\u0020the\u0020profile\u0020image\u0020of\u0020the\u0020logged\u002Din\u0020user.",
            "url": "classes/Controllers-UserController.html#method_updateProfileImage"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Log\u0020out\u0020the\u0020user.",
            "url": "classes/Controllers-UserController.html#method_logout"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/Controllers-UserController.html#property_page"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003A\u0024editorPage",
            "name": "editorPage",
            "summary": "",
            "url": "classes/Controllers-UserController.html#property_editorPage"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003A\u0024action",
            "name": "action",
            "summary": "",
            "url": "classes/Controllers-UserController.html#property_action"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/Controllers-UserController.html#property_username"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/Controllers-UserController.html#property_validator"
        },                {
            "fqsen": "\\Controllers\\UserController\u003A\u003A\u0024userRole",
            "name": "userRole",
            "summary": "",
            "url": "classes/Controllers-UserController.html#property_userRole"
        },                {
            "fqsen": "\\Helpers\\DateHelper",
            "name": "DateHelper",
            "summary": "DateHelper",
            "url": "classes/Helpers-DateHelper.html"
        },                {
            "fqsen": "\\Helpers\\DateHelper\u003A\u003AtoPrettyFormat\u0028\u0029",
            "name": "toPrettyFormat",
            "summary": "Convert\u0020a\u0020date\u0020from\u0020ISO\u0020format\u0020\u0028\u0060Y\u002Dm\u002Dd\u0060\u0029\u0020or\u0020a\u0020\u0060DateTime\u0060\u0020object\u0020to\u0020the\u0020pretty\u0020format\u0020\u0028\u0060d.m.Y\u0060\u0029.",
            "url": "classes/Helpers-DateHelper.html#method_toPrettyFormat"
        },                {
            "fqsen": "\\Helpers\\DateHelper\u003A\u003AtoISOFormat\u0028\u0029",
            "name": "toISOFormat",
            "summary": "Convert\u0020a\u0020date\u0020from\u0020pretty\u0020format\u0020\u0028\u0060d.m.Y\u0060\u0029\u0020or\u0020a\u0020\u0060DateTime\u0060\u0020object\u0020to\u0020ISO\u0020format\u0020\u0028\u0060Y\u002Dm\u002Dd\u0060\u0029.",
            "url": "classes/Helpers-DateHelper.html#method_toISOFormat"
        },                {
            "fqsen": "\\Helpers\\DateHelper\u003A\u003AifPrettyConvertToISO\u0028\u0029",
            "name": "ifPrettyConvertToISO",
            "summary": "Validate\u0020and\u0020convert\u0020a\u0020pretty\u0020format\u0020date\u0020\u0028\u0060d.m.Y\u0060\u0029\u0020to\u0020ISO\u0020format\u0020\u0028\u0060Y\u002Dm\u002Dd\u0060\u0029\u0020if\u0020applicable.",
            "url": "classes/Helpers-DateHelper.html#method_ifPrettyConvertToISO"
        },                {
            "fqsen": "\\Helpers\\DateHelper\u003A\u003APRETTY_FORMAT",
            "name": "PRETTY_FORMAT",
            "summary": "The\u0020format\u0020used\u0020for\u0020human\u002Dreadable\u0020\u0022pretty\u0022\u0020dates.",
            "url": "classes/Helpers-DateHelper.html#constant_PRETTY_FORMAT"
        },                {
            "fqsen": "\\Helpers\\DateHelper\u003A\u003AISO_FORMAT",
            "name": "ISO_FORMAT",
            "summary": "The\u0020format\u0020used\u0020for\u0020ISO\u002Dstandard\u0020dates.",
            "url": "classes/Helpers-DateHelper.html#constant_ISO_FORMAT"
        },                {
            "fqsen": "\\Helpers\\ImageHelper",
            "name": "ImageHelper",
            "summary": "ImageHelper",
            "url": "classes/Helpers-ImageHelper.html"
        },                {
            "fqsen": "\\Helpers\\ImageHelper\u003A\u003AgetGdImage\u0028\u0029",
            "name": "getGdImage",
            "summary": "Create\u0020a\u0020\u0060GdImage\u0060\u0020object\u0020from\u0020an\u0020uploaded\u0020file.",
            "url": "classes/Helpers-ImageHelper.html#method_getGdImage"
        },                {
            "fqsen": "\\Helpers\\ImageHelper\u003A\u003Aresize\u0028\u0029",
            "name": "resize",
            "summary": "Crop\u0020and\u0020resize\u0020an\u0020image\u0020to\u0020the\u0020specified\u0020dimensions.",
            "url": "classes/Helpers-ImageHelper.html#method_resize"
        },                {
            "fqsen": "\\Helpers\\ImageHelper\u003A\u003AisImageUploaded\u0028\u0029",
            "name": "isImageUploaded",
            "summary": "Check\u0020if\u0020an\u0020image\u0020file\u0020has\u0020been\u0020uploaded.",
            "url": "classes/Helpers-ImageHelper.html#method_isImageUploaded"
        },                {
            "fqsen": "\\Helpers\\ImageHelper\u003A\u003AsaveImage\u0028\u0029",
            "name": "saveImage",
            "summary": "Save\u0020a\u0020\u0060GdImage\u0060\u0020to\u0020a\u0020file.",
            "url": "classes/Helpers-ImageHelper.html#method_saveImage"
        },                {
            "fqsen": "\\Helpers\\ImageHelper\u003A\u003AgetUsableImageArray\u0028\u0029",
            "name": "getUsableImageArray",
            "summary": "Normalize\u0020a\u0020nested\u0020array\u0020of\u0020uploaded\u0020files\u0020into\u0020a\u0020usable\u0020array\u0020format.",
            "url": "classes/Helpers-ImageHelper.html#method_getUsableImageArray"
        },                {
            "fqsen": "\\Helpers\\ImageHelper\u003A\u003AprocessProfilePicture\u0028\u0029",
            "name": "processProfilePicture",
            "summary": "Process\u0020an\u0020uploaded\u0020image\u0020as\u0020a\u0020profile\u0020picture.",
            "url": "classes/Helpers-ImageHelper.html#method_processProfilePicture"
        },                {
            "fqsen": "\\Helpers\\ImageHelper\u003A\u003AprocessArticleImage\u0028\u0029",
            "name": "processArticleImage",
            "summary": "Process\u0020an\u0020uploaded\u0020image\u0020for\u0020an\u0020article.",
            "url": "classes/Helpers-ImageHelper.html#method_processArticleImage"
        },                {
            "fqsen": "\\Helpers\\ImageHelper\u003A\u003AgenerateThumbnail\u0028\u0029",
            "name": "generateThumbnail",
            "summary": "Generate\u0020a\u0020thumbnail\u0020image.",
            "url": "classes/Helpers-ImageHelper.html#method_generateThumbnail"
        },                {
            "fqsen": "\\Helpers\\PrivilegeRedirect",
            "name": "PrivilegeRedirect",
            "summary": "PrivilegeRedirect",
            "url": "classes/Helpers-PrivilegeRedirect.html"
        },                {
            "fqsen": "\\Helpers\\PrivilegeRedirect\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Helpers-PrivilegeRedirect.html#method___construct"
        },                {
            "fqsen": "\\Helpers\\PrivilegeRedirect\u003A\u003AredirectHost\u0028\u0029",
            "name": "redirectHost",
            "summary": "Redirect\u0020users\u0020who\u0020are\u0020not\u0020authenticated\u0020or\u0020lack\u0020privileges.",
            "url": "classes/Helpers-PrivilegeRedirect.html#method_redirectHost"
        },                {
            "fqsen": "\\Helpers\\PrivilegeRedirect\u003A\u003AredirectUser\u0028\u0029",
            "name": "redirectUser",
            "summary": "Redirect\u0020users\u0020who\u0020are\u0020not\u0020at\u0020least\u0020Editors.",
            "url": "classes/Helpers-PrivilegeRedirect.html#method_redirectUser"
        },                {
            "fqsen": "\\Helpers\\PrivilegeRedirect\u003A\u003AredirectEditor\u0028\u0029",
            "name": "redirectEditor",
            "summary": "Redirect\u0020users\u0020who\u0020are\u0020not\u0020Admins.",
            "url": "classes/Helpers-PrivilegeRedirect.html#method_redirectEditor"
        },                {
            "fqsen": "\\Helpers\\PrivilegeRedirect\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/Helpers-PrivilegeRedirect.html#property_user"
        },                {
            "fqsen": "\\Helpers\\ReplaceHelper",
            "name": "ReplaceHelper",
            "summary": "ReplaceHelper",
            "url": "classes/Helpers-ReplaceHelper.html"
        },                {
            "fqsen": "\\Helpers\\ReplaceHelper\u003A\u003AreplaceSpecialChars\u0028\u0029",
            "name": "replaceSpecialChars",
            "summary": "Replace\u0020special\u0020characters\u0020in\u0020a\u0020string\u0020with\u0020their\u0020ASCII\u0020equivalents.",
            "url": "classes/Helpers-ReplaceHelper.html#method_replaceSpecialChars"
        },                {
            "fqsen": "\\Helpers\\ReplaceHelper\u003A\u003AgetUrlFriendlyString\u0028\u0029",
            "name": "getUrlFriendlyString",
            "summary": "Convert\u0020a\u0020string\u0020into\u0020a\u0020URL\u002Dfriendly\u0020format.",
            "url": "classes/Helpers-ReplaceHelper.html#method_getUrlFriendlyString"
        },                {
            "fqsen": "\\Helpers\\UrlHelper",
            "name": "UrlHelper",
            "summary": "UrlHelper",
            "url": "classes/Helpers-UrlHelper.html"
        },                {
            "fqsen": "\\Helpers\\UrlHelper\u003A\u003AbaseUrl\u0028\u0029",
            "name": "baseUrl",
            "summary": "Get\u0020the\u0020base\u0020URL\u0020with\u0020an\u0020optional\u0020appended\u0020path.",
            "url": "classes/Helpers-UrlHelper.html#method_baseUrl"
        },                {
            "fqsen": "\\Logic\\Article",
            "name": "Article",
            "summary": "Article",
            "url": "classes/Logic-Article.html"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Article\u0020constructor.",
            "url": "classes/Logic-Article.html#method___construct"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetArticleBySlug\u0028\u0029",
            "name": "getArticleBySlug",
            "summary": "Retrieve\u0020an\u0020article\u0020from\u0020the\u0020database\u0020based\u0020on\u0020its\u0020slug.",
            "url": "classes/Logic-Article.html#method_getArticleBySlug"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetArticleById\u0028\u0029",
            "name": "getArticleById",
            "summary": "Retrieve\u0020an\u0020article\u0020from\u0020the\u0020database\u0020based\u0020on\u0020its\u0020ID.",
            "url": "classes/Logic-Article.html#method_getArticleById"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Logic-Article.html#method_getId"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Logic-Article.html#method_getTitle"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetSubtitle\u0028\u0029",
            "name": "getSubtitle",
            "summary": "",
            "url": "classes/Logic-Article.html#method_getSubtitle"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "",
            "url": "classes/Logic-Article.html#method_getContent"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetSlug\u0028\u0029",
            "name": "getSlug",
            "summary": "",
            "url": "classes/Logic-Article.html#method_getSlug"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetImagePaths\u0028\u0029",
            "name": "getImagePaths",
            "summary": "",
            "url": "classes/Logic-Article.html#method_getImagePaths"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetAuthorId\u0028\u0029",
            "name": "getAuthorId",
            "summary": "",
            "url": "classes/Logic-Article.html#method_getAuthorId"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "",
            "url": "classes/Logic-Article.html#method_getCreatedAt"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Logic-Article.html#property_id"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Logic-Article.html#property_title"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A\u0024subtitle",
            "name": "subtitle",
            "summary": "",
            "url": "classes/Logic-Article.html#property_subtitle"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/Logic-Article.html#property_content"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A\u0024slug",
            "name": "slug",
            "summary": "",
            "url": "classes/Logic-Article.html#property_slug"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A\u0024imagePaths",
            "name": "imagePaths",
            "summary": "",
            "url": "classes/Logic-Article.html#property_imagePaths"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A\u0024authorId",
            "name": "authorId",
            "summary": "",
            "url": "classes/Logic-Article.html#property_authorId"
        },                {
            "fqsen": "\\Logic\\Article\u003A\u003A\u0024createdAt",
            "name": "createdAt",
            "summary": "",
            "url": "classes/Logic-Article.html#property_createdAt"
        },                {
            "fqsen": "\\Logic\\DatabaseException",
            "name": "DatabaseException",
            "summary": "DatabaseException",
            "url": "classes/Logic-DatabaseException.html"
        },                {
            "fqsen": "\\Logic\\DatabaseException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020the\u0020custom\u0020exception.",
            "url": "classes/Logic-DatabaseException.html#method___construct"
        },                {
            "fqsen": "\\Logic\\IncorrectInputException",
            "name": "IncorrectInputException",
            "summary": "IncorrectInputException",
            "url": "classes/Logic-IncorrectInputException.html"
        },                {
            "fqsen": "\\Logic\\IncorrectInputException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020the\u0020custom\u0020exception.",
            "url": "classes/Logic-IncorrectInputException.html#method___construct"
        },                {
            "fqsen": "\\Logic\\Router",
            "name": "Router",
            "summary": "Router",
            "url": "classes/Logic-Router.html"
        },                {
            "fqsen": "\\Logic\\Router\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "Redirects\u0020the\u0020user\u0020to\u0020a\u0020specific\u0020path,\u0020optionally\u0020appending\u0020query\u0020parameters.",
            "url": "classes/Logic-Router.html#method_redirect"
        },                {
            "fqsen": "\\Logic\\Router\u003A\u003Aroute\u0028\u0029",
            "name": "route",
            "summary": "Routes\u0020an\u0020HTTP\u0020request\u0020to\u0020the\u0020appropriate\u0020controller\u0020and\u0020method\u0020based\u0020on\u0020the\u0020URL\u0020and\u0020method.",
            "url": "classes/Logic-Router.html#method_route"
        },                {
            "fqsen": "\\Logic\\Router\u003A\u003AGET\u0028\u0029",
            "name": "GET",
            "summary": "Handle\u0020\u0060GET\u0060\u0020requests\u0020and\u0020route\u0020them\u0020to\u0020the\u0020appropriate\u0020controller.",
            "url": "classes/Logic-Router.html#method_GET"
        },                {
            "fqsen": "\\Logic\\Router\u003A\u003APOST\u0028\u0029",
            "name": "POST",
            "summary": "Handle\u0020\u0060POST\u0060\u0020requests\u0020and\u0020route\u0020them\u0020to\u0020the\u0020appropriate\u0020controller\u0027s\u0020method.",
            "url": "classes/Logic-Router.html#method_POST"
        },                {
            "fqsen": "\\Logic\\User",
            "name": "User",
            "summary": "User",
            "url": "classes/Logic-User.html"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "User\u0020constructor.",
            "url": "classes/Logic-User.html#method___construct"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AgetUserByUsername\u0028\u0029",
            "name": "getUserByUsername",
            "summary": "Fetch\u0020a\u0020\u0060User\u0060\u0020object\u0020from\u0020the\u0020database\u0020using\u0020the\u0020username.",
            "url": "classes/Logic-User.html#method_getUserByUsername"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AgetUserById\u0028\u0029",
            "name": "getUserById",
            "summary": "Fetch\u0020a\u0020\u0060User\u0060\u0020object\u0020from\u0020the\u0020database\u0020using\u0020the\u0020user\u0027s\u0020ID.",
            "url": "classes/Logic-User.html#method_getUserById"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AisAdmin\u0028\u0029",
            "name": "isAdmin",
            "summary": "Check\u0020if\u0020the\u0020user\u0020has\u0020an\u0020admin\u0020or\u0020owner\u0020role.",
            "url": "classes/Logic-User.html#method_isAdmin"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AisEditor\u0028\u0029",
            "name": "isEditor",
            "summary": "Check\u0020if\u0020the\u0020user\u0020has\u0020permission\u0020to\u0020edit\u0020articles.",
            "url": "classes/Logic-User.html#method_isEditor"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Logic-User.html#method_getId"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "",
            "url": "classes/Logic-User.html#method_getUsername"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AgetFullname\u0028\u0029",
            "name": "getFullname",
            "summary": "",
            "url": "classes/Logic-User.html#method_getFullname"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AsetFullname\u0028\u0029",
            "name": "setFullname",
            "summary": "",
            "url": "classes/Logic-User.html#method_setFullname"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AgetImage\u0028\u0029",
            "name": "getImage",
            "summary": "",
            "url": "classes/Logic-User.html#method_getImage"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AsetImage\u0028\u0029",
            "name": "setImage",
            "summary": "Update\u0020the\u0020path\u0020of\u0020the\u0020user\u0027s\u0020profile\u0020image.",
            "url": "classes/Logic-User.html#method_setImage"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AgetRole\u0028\u0029",
            "name": "getRole",
            "summary": "",
            "url": "classes/Logic-User.html#method_getRole"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "",
            "url": "classes/Logic-User.html#method_getCreatedAt"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Logic-User.html#property_id"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/Logic-User.html#property_username"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003A\u0024fullname",
            "name": "fullname",
            "summary": "",
            "url": "classes/Logic-User.html#property_fullname"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003A\u0024image",
            "name": "image",
            "summary": "",
            "url": "classes/Logic-User.html#property_image"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003A\u0024role",
            "name": "role",
            "summary": "",
            "url": "classes/Logic-User.html#property_role"
        },                {
            "fqsen": "\\Logic\\User\u003A\u003A\u0024createdAt",
            "name": "createdAt",
            "summary": "",
            "url": "classes/Logic-User.html#property_createdAt"
        },                {
            "fqsen": "\\Logic\\Validator",
            "name": "Validator",
            "summary": "Validator",
            "url": "classes/Logic-Validator.html"
        },                {
            "fqsen": "\\Logic\\Validator\u003A\u003AthrowExceptionOnError\u0028\u0029",
            "name": "throwExceptionOnError",
            "summary": "Throw\u0020an\u0020exception\u0020if\u0020there\u0020are\u0020validation\u0020errors.",
            "url": "classes/Logic-Validator.html#method_throwExceptionOnError"
        },                {
            "fqsen": "\\Logic\\Validator\u003A\u003AvalidateUserCredentials\u0028\u0029",
            "name": "validateUserCredentials",
            "summary": "Validate\u0020user\u0020credentials\u0020against\u0020the\u0020database.",
            "url": "classes/Logic-Validator.html#method_validateUserCredentials"
        },                {
            "fqsen": "\\Logic\\Validator\u003A\u003AvalidateUsername\u0028\u0029",
            "name": "validateUsername",
            "summary": "Validate\u0020the\u0020format\u0020and\u0020existence\u0020of\u0020a\u0020username.",
            "url": "classes/Logic-Validator.html#method_validateUsername"
        },                {
            "fqsen": "\\Logic\\Validator\u003A\u003AvalidateFullname\u0028\u0029",
            "name": "validateFullname",
            "summary": "Validate\u0020the\u0020format\u0020and\u0020length\u0020of\u0020a\u0020fullname.",
            "url": "classes/Logic-Validator.html#method_validateFullname"
        },                {
            "fqsen": "\\Logic\\Validator\u003A\u003AvalidatePassword\u0028\u0029",
            "name": "validatePassword",
            "summary": "Validate\u0020a\u0020password\u0020and\u0020its\u0020confirmation.",
            "url": "classes/Logic-Validator.html#method_validatePassword"
        },                {
            "fqsen": "\\Logic\\Validator\u003A\u003AvalidateImage\u0028\u0029",
            "name": "validateImage",
            "summary": "Validate\u0020an\u0020uploaded\u0020image\u0027s\u0020size,\u0020format,\u0020and\u0020dimensions.",
            "url": "classes/Logic-Validator.html#method_validateImage"
        },                {
            "fqsen": "\\Logic\\Validator\u003A\u003AvalidateArticle\u0028\u0029",
            "name": "validateArticle",
            "summary": "Validate\u0020an\u0020article\u0027s\u0020title,\u0020subtitle,\u0020and\u0020content.",
            "url": "classes/Logic-Validator.html#method_validateArticle"
        },                {
            "fqsen": "\\Models\\ArticleModel",
            "name": "ArticleModel",
            "summary": "ArticleModel",
            "url": "classes/Models-ArticleModel.html"
        },                {
            "fqsen": "\\Models\\ArticleModel\u003A\u003AinsertArticle\u0028\u0029",
            "name": "insertArticle",
            "summary": "Insert\u0020a\u0020new\u0020article\u0020into\u0020the\u0020database.",
            "url": "classes/Models-ArticleModel.html#method_insertArticle"
        },                {
            "fqsen": "\\Models\\ArticleModel\u003A\u003AselectArticle\u0028\u0029",
            "name": "selectArticle",
            "summary": "Retrieve\u0020a\u0020single\u0020article\u0020from\u0020the\u0020database\u0020based\u0020on\u0020conditions.",
            "url": "classes/Models-ArticleModel.html#method_selectArticle"
        },                {
            "fqsen": "\\Models\\ArticleModel\u003A\u003AselectArticles\u0028\u0029",
            "name": "selectArticles",
            "summary": "Retrieve\u0020all\u0020articles\u0020from\u0020the\u0020database,\u0020with\u0020optional\u0020filtering\u0020conditions.",
            "url": "classes/Models-ArticleModel.html#method_selectArticles"
        },                {
            "fqsen": "\\Models\\ArticleModel\u003A\u003AupdateArticle\u0028\u0029",
            "name": "updateArticle",
            "summary": "Update\u0020an\u0020existing\u0020article\u0020in\u0020the\u0020database.",
            "url": "classes/Models-ArticleModel.html#method_updateArticle"
        },                {
            "fqsen": "\\Models\\ArticleModel\u003A\u003AremoveArticle\u0028\u0029",
            "name": "removeArticle",
            "summary": "Remove\u0020an\u0020article\u0020from\u0020the\u0020database.",
            "url": "classes/Models-ArticleModel.html#method_removeArticle"
        },                {
            "fqsen": "\\Models\\DatabaseConnector",
            "name": "DatabaseConnector",
            "summary": "DatabaseConnector",
            "url": "classes/Models-DatabaseConnector.html"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Initialize\u0020the\u0020database\u0020settings\u0020by\u0020loading\u0020credentials\u0020from\u0020environment\u0020variables.",
            "url": "classes/Models-DatabaseConnector.html#method_init"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003Aconnect\u0028\u0029",
            "name": "connect",
            "summary": "Establish\u0020a\u0020PDO\u0020connection\u0020to\u0020the\u0020database.",
            "url": "classes/Models-DatabaseConnector.html#method_connect"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020database\u0020connection.",
            "url": "classes/Models-DatabaseConnector.html#method_close"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003Aselect\u0028\u0029",
            "name": "select",
            "summary": "Perform\u0020a\u0020SELECT\u0020query\u0020on\u0020the\u0020database.",
            "url": "classes/Models-DatabaseConnector.html#method_select"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "Insert\u0020a\u0020new\u0020record\u0020into\u0020a\u0020database\u0020table.",
            "url": "classes/Models-DatabaseConnector.html#method_insert"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020existing\u0020records\u0020in\u0020a\u0020database\u0020table.",
            "url": "classes/Models-DatabaseConnector.html#method_update"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Delete\u0020records\u0020from\u0020a\u0020database\u0020table\u0020based\u0020on\u0020conditions.",
            "url": "classes/Models-DatabaseConnector.html#method_remove"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "Count\u0020the\u0020number\u0020of\u0020rows\u0020in\u0020a\u0020database\u0020table.",
            "url": "classes/Models-DatabaseConnector.html#method_count"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003AselectMaxId\u0028\u0029",
            "name": "selectMaxId",
            "summary": "Retrieve\u0020the\u0020highest\u0020ID\u0020from\u0020a\u0020database\u0020table.",
            "url": "classes/Models-DatabaseConnector.html#method_selectMaxId"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003AresetAutoIncrement\u0028\u0029",
            "name": "resetAutoIncrement",
            "summary": "Reset\u0020the\u0020AUTO_INCREMENT\u0020counter\u0020for\u0020a\u0020table.",
            "url": "classes/Models-DatabaseConnector.html#method_resetAutoIncrement"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003A\u0024server",
            "name": "server",
            "summary": "",
            "url": "classes/Models-DatabaseConnector.html#property_server"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003A\u0024dbname",
            "name": "dbname",
            "summary": "",
            "url": "classes/Models-DatabaseConnector.html#property_dbname"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/Models-DatabaseConnector.html#property_username"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/Models-DatabaseConnector.html#property_password"
        },                {
            "fqsen": "\\Models\\DatabaseConnector\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/Models-DatabaseConnector.html#property_connection"
        },                {
            "fqsen": "\\Models\\UserModel",
            "name": "UserModel",
            "summary": "UserModel",
            "url": "classes/Models-UserModel.html"
        },                {
            "fqsen": "\\Models\\UserModel\u003A\u003AselectUser\u0028\u0029",
            "name": "selectUser",
            "summary": "Retrieve\u0020a\u0020single\u0020user\u0020from\u0020the\u0020database.",
            "url": "classes/Models-UserModel.html#method_selectUser"
        },                {
            "fqsen": "\\Models\\UserModel\u003A\u003AselectUsers\u0028\u0029",
            "name": "selectUsers",
            "summary": "Retrieve\u0020all\u0020users\u0020from\u0020the\u0020database.",
            "url": "classes/Models-UserModel.html#method_selectUsers"
        },                {
            "fqsen": "\\Models\\UserModel\u003A\u003AexistsUser\u0028\u0029",
            "name": "existsUser",
            "summary": "Check\u0020if\u0020a\u0020user\u0020exists\u0020in\u0020the\u0020database\u0020by\u0020their\u0020username.",
            "url": "classes/Models-UserModel.html#method_existsUser"
        },                {
            "fqsen": "\\Models\\UserModel\u003A\u003AinsertUser\u0028\u0029",
            "name": "insertUser",
            "summary": "Insert\u0020a\u0020new\u0020user\u0020into\u0020the\u0020database.",
            "url": "classes/Models-UserModel.html#method_insertUser"
        },                {
            "fqsen": "\\Models\\UserModel\u003A\u003AupdateUserFullname\u0028\u0029",
            "name": "updateUserFullname",
            "summary": "Update\u0020a\u0020user\u0027s\u0020full\u0020name\u0020in\u0020the\u0020database.",
            "url": "classes/Models-UserModel.html#method_updateUserFullname"
        },                {
            "fqsen": "\\Models\\UserModel\u003A\u003AupdateUserProfileImage\u0028\u0029",
            "name": "updateUserProfileImage",
            "summary": "Update\u0020a\u0020user\u0027s\u0020profile\u0020image\u0020path\u0020in\u0020the\u0020database.",
            "url": "classes/Models-UserModel.html#method_updateUserProfileImage"
        },                {
            "fqsen": "\\ROOT",
            "name": "ROOT",
            "summary": "Absolute\u0020path\u0020to\u0020the\u0020root\u0020directory\u0020of\u0020the\u0020application.",
            "url": "namespaces/default.html#constant_ROOT"
        },                {
            "fqsen": "\\VIEWS",
            "name": "VIEWS",
            "summary": "Absolute\u0020path\u0020to\u0020the\u0020Views\u0020directory\u0020of\u0020the\u0020application.",
            "url": "namespaces/default.html#constant_VIEWS"
        },                {
            "fqsen": "\\BASE_URL",
            "name": "BASE_URL",
            "summary": "The\u0020base\u0020URL\u0020of\u0020the\u0020application.\u0020Defaults\u0020to\u0020an\u0020empty\u0020string\u0020\u0028root\u0029.",
            "url": "namespaces/default.html#constant_BASE_URL"
        },                {
            "fqsen": "\\DEFAULT_PFP",
            "name": "DEFAULT_PFP",
            "summary": "The\u0020default\u0020profile\u0020picture\u0020path\u0020for\u0020user\u0020accounts.",
            "url": "namespaces/default.html#constant_DEFAULT_PFP"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/controllers.html"
        },                {
            "fqsen": "\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/helpers.html"
        },                {
            "fqsen": "\\Logic",
            "name": "Logic",
            "summary": "",
            "url": "namespaces/logic.html"
        },                {
            "fqsen": "\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/models.html"
        }            ]
);
