<?php
/**
 * <h1>Application configuration</h1>
 * <p><strong>Do not edit this file</strong>, the data set here a crucial for the application to work properly.</p>
 * <hr>
 * <p>If you want to change the configuration, create a new file called config.local.php in the same directory and set the values there.</p>
 */



// Set global configs
const ROOT = __DIR__ . '/../';
const VIEWS = ROOT . 'src/Views/';

$_ENV['database'] = [
    'server' => 'localhost',
    'dbname' => 'vanekeri',
    'username' => 'vanekeri',
    'password' => 'petrpaveluwu',
];

// Set upload files permissions
ini_set('file_uploads', '1');
ini_set('upload_max_filesize', '1M');  // Max file size for uploads
ini_set('post_max_size', '1M');        // Max POST data size
ini_set('max_execution_time', '30');    // Max script execution time in seconds
ini_set('max_input_time', '60');



// Load local configuration
if (file_exists(ROOT . 'www/config.local.php')) {
    require ROOT . 'www/config.local.php';
    return;
}



// Set error reporting TODO: Remove for deployment
ini_set('display_errors', '1');
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

if (!defined('BASE_URL')) {
    define('BASE_URL', '');
}
